export const sizeConfigs = {
        small: {
            container: "h-55 w-40 rounded-2xl",
            padding: "px-4 pt-4 mb-2",
            iconSize: 10,
            categoryText: "text-[8px]",
            illusContainer: "h-45 bottom-1",
            kanbanImg: "h-40 bottom-6 w-full left-1/2 -translate-x-1/2",
            speakerImg: "h-58 bottom-6 w-full left-1/2 -translate-x-1/2",
            buildingImg: "h-62 bottom-8 w-full left-1/2 -translate-x-1/2",
            contentBox: "h-27 bottom-1",
            numberText: "text-3xl",
            titleText: "text-sm",
            bodyText: "text-[6px] leading-tight",
            backHeader: "mb-2",
            backIllustration: "h-8",
            backTitle: "text-sm",
            backContent: "text-[7px]"
        },
        medium: {
            container: "h-82.5 w-60.5 rounded-3xl",
            padding: "px-6 pt-6 mb-4",
            iconSize: 12,
            categoryText: "text-xs",
            illusContainer: "h-67.5 bottom-1.5",
            kanbanImg: "h-63.75 bottom-9 w-full left-1/2 -translate-x-1/2",
            speakerImg: "h-92 bottom-9 w-full left-1/2 -translate-x-1/2",
            buildingImg: "h-98 bottom-12 w-full left-1/2 -translate-x-1/2",
            contentBox: "h-40.5 bottom-1.5",
            numberText: "text-4xl",
            titleText: "text-xl",
            bodyText: "text-[9px]",
            backHeader: "mb-3",
            backIllustration: "h-12",
            backTitle: "text-lg",
            backContent: "text-[9px]"
        },
        big: {
            container: "h-99 w-70 rounded-[36px] overflow-hidden",
            padding: "px-7 pt-7 mb-4",
            iconSize: 14,
            categoryText: "text-sm",
            illusContainer: "h-60 bottom-1",
            kanbanImg: "h-60 bottom-4 w-full left-8 -translate-x-2",
            speakerImg: "h-70 bottom-0 w-full left-42 -translate-x-1/2",
            buildingImg: "h-66 bottom-0.5 w-full left-42 -translate-x-1/2",
            contentBox: "h-50 bottom-1.8",
            numberText: "text-5xl",
            titleText: "text-xl",
            bodyText: "text-[10px]",
            backHeader: "mb-3.5",
            backIllustration: "h-14",
            backTitle: "text-xl",
            backContent: "text-[10px]"
        },
        large: {
            container: "h-110.25 w-80.75 rounded-4xl overflow-hidden",
            padding: "px-8 pt-8 mb-3",
            iconSize: 16,
            categoryText: "text-sm",
            illusContainer: "h-90 bottom-2",
            kanbanImg: "h-90 bottom-24 w-full left-9 -translate-x-2",
            speakerImg: "h-80 bottom-16 w-full left-10 -translate-x-2",
            buildingImg: "h-90 bottom-10 w-full left-10 -translate-x-2",
            contentBox: "h-54 bottom-2",
            numberText: "text-6xl",
            titleText: "text-2xl",
            bodyText: "text-xs",
            backHeader: "mb-2",
            backIllustration: "h-16",
            backTitle: "text-xl",
            backContent: "text-[11px]"
        },
        extraLarge: {
            container: "h-126 w-88 rounded-4xl overflow-hidden",
            padding: "px-8 pt-8 mb-3",
            iconSize: 16,
            categoryText: "text-sm",
            illusContainer: "h-90 bottom-2",
            kanbanImg: "h-90 bottom-12 w-full left-9 -translate-x-2",
            speakerImg: "h-80 bottom-4 w-full left-13 -translate-x-2",
            buildingImg: "h-90 bottom-2 w-full left-9 -translate-x-2",
            contentBox: "h-54 bottom-2",
            numberText: "text-6xl",
            titleText: "text-2xl",
            bodyText: "text-xs",
            backHeader: "mb-2",
            backIllustration: "h-16",
            backTitle: "text-xl",
            backContent: "text-[11px]"
        }
    };